app/Http/routes.php
<?php

Route::get('/'      ,'FrontController@index');
Route::get('citas'  ,'FrontController@citas');
Route::get('login'  ,'FrontController@login');
Route::get('oct'    ,'FrontController@oct');
Route::get('admin'  ,'FrontController@admin');

Route::get('menus', 'MenuController@listing');
Route::resource('menu', 'MenuController');

Route::get('password/reset/{token}','Auth\PasswordController@getReset');
Route::post('password/reset','Auth\PasswordController@postReset');

Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

Route::resource('examen', 'PostController');
Route::get('examen/{slug}', ['as' => 'examen', 'uses' => 'PostController@show']);

Route::resource('image', 'ImageController');

Route::resource('user', 'UserController');

Route::resource('log' , 'LogController');
Route::get('logout'   , 'LogController@logout');

Route::resource('mail', 'MailController');

app/Post.php
<?php

namespace examenesApp;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Carbon\Carbon;
use DB;
class Post extends Model
{
  use Sluggable;
  public function sluggable()
  {
      return [
          'slug' => [
              'source' => 'title'
          ]
      ];
  }
    protected $table="posts";
    protected $fillable=['title','slug','content','menu_id'];

    public function images(){
      return $this->hasMany('examenesApp\Image');
    }
    public function menu(){
      return $this->belongsTo('examenesApp\Menu');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace examenesApp\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Route;
use examenesApp\Http\Requests;
use examenesApp\Http\Requests\PostRequest;
use examenesApp\Http\Controllers\Controller;
use Session;
use Redirect;
use Response;
use DB;
use examenesApp\Menu;
use examenesApp\Post;
use examenesApp\Image;

class PostController extends Controller
{
  public function __construct(){
    $this->middleware('auth',['only'=>['create','store','edit','update','destroy','index']]);
  }
    public function index()
    {
      $posts = Post::with(['menu'])->orderBy('title', 'asc')->get();
      return view('post.index', compact('posts'));
    }

    public function create()
    {
      $menus=Menu::lists('menu','id');
      return view('post.create', compact('menus'));
    }

    public function store(PostRequest $request)
    {
      $id=Post::create([
        'title'=>$request->title,
        'content'=>$request->content,
        'menu_id'=>$request->menu_id,
      ])->id;
      if ($request->name1) {
        Image::create([
          'route'=>$request->name1,
          'alt'=>$request->alt1,
          'post_id'=>$id,
        ]);
      }
      if ($request->name2) {
        Image::create([
          'route'=>$request->name2,
          'alt'=>$request->alt2,
          'post_id'=>$id,
        ]);
      }
      if ($request->name3) {
        Image::create([
          'route'=>$request->name3,
          'alt'=>$request->alt3,
          'post_id'=>$id,
        ]);
      }
      flash('Examen agregado correctamente','success')->important();
      return Redirect::to('/examen');
    }

    public function show($slug)
    {
      $menus=Menu::All();
      $posts = DB::table('posts')
                ->orderBy('title', 'asc')
                ->get();

      $post = Post::where('slug','=', $slug)->firstOrFail();
      $images = Image::where('post_id','=', $post->id)->get();
      $images_number = Image::where('post_id','=', $post->id)->count();
      return view("post.view", compact('menus','combo','posts','images','images_number'), ['post'=>$post]);
    }

    public function edit($id)
    {
        $menus=Menu::lists('menu','id');
        $post=Post::find($id);
        $images=Image::where('post_id','=', $id)->get();
        return view('post.edit', compact('images'),['post'=>$post,'menus'=>$menus]);
    }

    public function update(Request $request, $id)
    {
      $post=Post::find($id);
      $post->slug= null;
      $post->fill($request->all());
      $post->save();
      // ====================================================================
      $imagen=array(
        $request->image_id0,
        $request->image_id1,
        $request->image_id2,
      );
      $rutas=array(
        $request->image0,
        $request->image1,
        $request->image2,
      );
      $alts=array(
        $request->alt0,
        $request->alt1,
        $request->alt2,
      );
      for ($i=0; $i < 3; $i++)
      {
        $Image=Image::find($imagen[$i]);
        if (!empty($Image->route) && !empty($request->file('image'.$i)))
        {
          \Storage::delete($Image->route);
          $Image->route=$rutas[$i];
          $Image->alt=$alts[$i];
          $Image->save();
        }

      }
      //======================================================================
      // $Image1=Image::find($request->image_id0);
      // if (!empty($Image1->route) && !empty($request->file('image0'))) {
      //   \Storage::delete($Image1->route);
      //   $Image1->route=$request->image0;
      //   $Image1->alt=$request->alt0;
      //   $Image1->save();
      // }
      // $Image2=Image::find($request->image_id1);
      // if (!empty($Image2->route) && !empty($request->file('image1'))) {
      //   \Storage::delete($Image2->route);
      //   $Image2->route=$request->image1;
      //   $Image2->alt=$request->alt1;
      //   $Image2->save();
      // }
      // $Image3=Image::find($request->image_id2);
      // if (!empty($Image3->route) && !empty($request->file('image2'))) {
      //   \Storage::delete($Image3->route);
      //   $Image3->route=$request->image2;
      //   $Image3->alt=$request->alt2;
      //   $Image3->save();
      // }
      // // ======================================================================
      flash('Examen actualizado correctamente','success')->important();
      return Redirect::to('/examen');
    }

    public function destroy($id)
    {
      $post=Post::find($id);
      $images = Image::where('post_id','=', $post->id)->get();
      foreach ($images as $image) {
        if (empty($image)) {
          \Storage::delete($image->route);
        }
      }
      $post->delete();
      flash('Examen eliminado correctamente','success');
      return Redirect::to('/examen');
    }
}

resources/views/post/create.blade.php
@extends('layouts.dashboard')
@section('section')
  @include('request')
  @include('flash::message')
  {!!Form::open(['route'=>'examen.store','method'=>'POST', 'files'=>true])!!}
    @include('post.forms.post')
    <div class="row">

      <div class="col-xs-4">
        <div class="form-group div_file">
          <p class="glyphicon glyphicon-picture" ></p>
          {!! Form::file('name1', ['class' => 'input_file']) !!}
        </div>
        <div class="form-group">
          {!!Form::label('content','Descripción de la imagen')!!}
          {!!Form::text('alt1', null,['class'=>'form-control', 'placeholder'=>'Ingrese la descripcion de la imagen'])!!}
        </div>
      </div>

      <div class="col-xs-4">
        <div class="form-group div_file">
          <p class="glyphicon glyphicon-picture" ></p>
          {!! Form::file('name2', ['class' => 'input_file']) !!}
        </div>
        <div class="form-group">
          {!!Form::label('content','Descripción de la imagen')!!}
          {!!Form::text('alt2', null,['class'=>'form-control', 'placeholder'=>'Ingrese la descripcion de la imagen'])!!}
        </div>
      </div>

      <div class="col-xs-4">
        <div class="form-group div_file">
          <p class="glyphicon glyphicon-picture" ></p>
          {!! Form::file('name3', ['class' => 'input_file']) !!}
        </div>
        <div class="form-group">
          {!!Form::label('content','Descripción de la imagen')!!}
          {!!Form::text('alt3', null,['class'=>'form-control', 'placeholder'=>'Ingrese la descripcion de la imagen'])!!}
        </div>
      </div>

    </div>

    <div class="form-group text-right">
      {!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}
    </div>
  {!!Form::close()!!}
@endsection

resources/views/post/edit.blade.php
@extends('layouts.dashboard')
@section('section')
  @include('request')
  {!!Form::model($post,['route'=>['examen.update',$post->id],'method'=>'PUT','files'=>true])!!}
    @include('post.forms.post')
    @if(Auth::user()->role == 'ROLE_ILUSTRATOR' || Auth::user()->role == 'ROLE_ADMIN' )
        <div class="row">
          @for ($i=0; $i<$images->count(); $i++)
            <div class="col-xs-4">
              <input type="file" name="image{{$i}}">
              <input type="hidden" name="image_id{{$i}}" value="{{$images[$i]->id}}">
              <img src= {{asset('posts/'. $images[$i]->route)}} class="img-thumbnail img-responsive miniatura" alt="" /><br>
              <input type="text" name="alt{{$i}}" value="{{$images[$i]->alt}}" class="form-control">
            </div>
          @endfor
        </div>
    @endif
    <div class="form-group text-right">
      {!!Form::submit('Actualizar',['class'=>'btn btn-primary'])!!}
    </div>
  {!!Form::close()!!}
@endsection

resources/views/post/index.blade.php
@extends('layouts.dashboard')
@section('section')
  @include('flash::message')
  <table class="table">
    <thead>
      <th>Nombre</th>
      <th>Menu</th>
      <th>Operaciones</th>
    </thead>
    @foreach ($posts as $post)
      <tbody>
        <td>{{$post->title}}</td>
        <td>{{$post->menu->menu}}</td>
        <td>
          {!!Form::open(['route'=>['examen.destroy',$post->id], 'method'=>'DELETE'])!!}
            <div class="form-group">
              <a href="{{ route('examen.edit', $post->id) }}"><i class="btn btn-primary glyphicon glyphicon-pencil"></i></a>
                {!! Form::button('<span class="glyphicon glyphicon-trash"></span>',
                [
                    'type' => 'button',
                    'class'=>'btn btn-danger',
                    'onclick' => 'if(confirm("¿Realmente desea eliminar este elemento? ")) {  $(form).submit(); }',
                ]) !!}
            </div>
          {!!Form::close()!!}
        </td>
      </tbody>
    @endforeach
  </table>
@endsection

resources/views/post/view.blade.php
@extends('layouts.main')
@section('section')
  <div class="row" style="background-color:white;">

    <ol class="breadcrumb">
      <li><a href="{!!URL::to('/')!!}">Inicio</a></li>
      @foreach ($menus as $menu)
        @if($post->menu_id==$menu->id)
          <li class="active">{{$menu->menu}}</li>
        @endif
      @endforeach
      <li class="active">{{$post->title}}</li>
    </ol>

    <article class="container" style="margin-bottom:5em;">
      <div class="row" style="margin-bottom:5em;">

        <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5 text-left">
          @foreach ($menus as $menu)
            @if($post->menu_id==$menu->id && $post->menu_id<>5)
              <img src= {{asset('img/'. $menu->icon)}} class="img ver-miniatura" alt="" />
            @endif
          @endforeach
          @foreach ($images as $image)
            @if ($image->route && $image->post->menu_id==5)
              <img src= {{asset('posts/'. $image->route)}} class="img-thumbnail img-responsive miniatura" alt="" /><br>
              <label for="" style="padding:0.5em">{{$image->alt}}</label>
            @endif
          @endforeach
        </div>

        <article class="col-xs-12 col-sm-7 col-md-7 col-lg-7">
          <h1 class="ver-h1"> {!!$post->title!!} </h1>
          <p>  {!!$post->content!!} </p>
        </article>

      </div>

      <div class="row">
        @for ($i=0; $i < $images_number; $i++)
          @if($images_number==2)

            @if ($i==0)
              <div class="col-xs-12 col-sm-4 text-center">
                <img src= {{asset('posts/'. $images[$i]->route)}} class="img-thumbnail  miniatura" alt="" /><br>
                <label for="" style="padding:0.5em">{{$images[$i]->alt}}</label>
              </div>
            @else
              <div class="col-xs-12 col-sm-8 text-center">
                <img src= {{asset('posts/'. $images[$i]->route)}} class="img-thumbnail  miniatura2" alt="" /><br>
                <label for="" style="padding:0.5em">{{$images[$i]->alt}}</label>
              </div>
            @endif

          @elseif($images[$i]->post->menu_id<>5)
            <div class="col-xs-12 col-sm-4 text-center">
              <img src= {{asset('posts/'. $images[$i]->route)}} class="img-thumbnail  miniatura" alt="" /><br>
              <label for="" style="padding:0.5em">{{$images[$i]->alt}}</label>
            </div>
          @endif

        @endfor
      </div>
    </article>
  </div>


@endsection